li = ["What is the duration of each program?",
"What are the prerequisites to join corporate programs of Race?",
"Maximum number of participants for each program of RACE",
"What about the program delivery modes of RACE programs?",
"Do I have the option of completing the RACE programs online?",
"How do I register for the program of RACE I am interested in?",
"Do you provide learning materials to the program participants of RACE?",
"What kind of infrastructure facilities can I expect at RACE?",
"Am I eligible for any discounts to join RACE programs?",
"What are the tools used for hands-on learning in RACE programs?",
"Is it possible to attend a classroom session before joining the RACE program?",
"What can I expect after the completion of the RACE program?",
"What about the admission cycle of RACE programs?",
"How many seats are available for long-term programs of RACE?",
"Is it possible to pay the fees in instalments for RACE program?",
"Do you offer placement assistance at RACE?",
"Why should I join MS in Business Analytics program of RACE?",
"What is the scope of business analytics?",
"When do the admissions for the MS in Business Analytics start at RACE?",
"Prerequisites to join MS in Business Analytics of RACE",
"Is industry experience mandatory for MS in Business Analytics of RACE?",
"How can I learn more about the MS in Business Analytics program of RACE?",
"What is the duration of the MS in Business Analytics program of RACE?",
"Is the MS in Business Analytics program of RACE recognized?",
"How do you promote experiential learning in MS in Business Analytics of RACE?",
"Do you have certification programs in analytics of RACE?",
"How an M. Tech. in Artificial Intelligence program of RACE helps me?",
"Who can apply to M. Tech in AI of RACE?",
"Who can apply to M. Sc. in AI?",
"What subjects do I study in Artificial Intelligence of RACE?",
"How does RACE deliver artificial intelligence programs?",
"Are there any artificial intelligence courses offered online by RACE?",
"What is the demand for artificial intelligence professionals?",
"What is the duration of RACE’s artificial intelligence programs?",
"When does the new batches for Artificial intelligence programs start at RACE?",
"Is industry experience mandatory for joining AI programs of RACE?",
"Is M. Tech in Artificial intelligence program of RACE accredited?",
"How can I learn more about the Artificial intelligence programs of RACE?",
"How do RACE promotes experiential learning in Artificial intelligence?",
"Do you have certification programs in artificial intelligence at RACE?",
"Why should I learn M. Tech in Cybersecurity at RACE?",
"Why should I learn M.Sc. in Cybersecurity at RACE?",
"Why should I learn PGD in Cybersecurity of RACE?",
"Explain the difference between M. Tech and M.Sc. in cybersecurity?",
"Are there any cybersecurity courses offered online by RACE?",
"What is the demand for cybersecurity professionals?",
"What is the duration of RACE’s cybersecurity programs?",
"When do you start new batches for Cybersecurity programs at RACE?",
"Is industry experience mandatory for joining AI programs of RACE?",
"Is the M. Tech in Cybersecurity program of RACE accredited?",
"How can I learn more about M. Tech in Cybersecurity program of RACE?",
"Want to learn more about M. Sc. in Cybersecurity program of RACE?",
"How can I learn more about PGD in Cybersecurity program of RACE?",
"Do you have certification programs in the cybersecurity domain of RACE?",
"How do you promote experiential learning in Cybersecurity programs of RACE?",
"Why do I learn M. Sc. in Cloud Architecture and Security at RACE?",
"Who can apply to M. Sc. in Cloud Architecture and Security program of RACE? ",
"What are the subjects taught under the M. Sc. in Cloud Architecture and Security of RACE?",
"What is the mode of program delivery of M. Sc. in Cloud Architecture and Security of RACE?",
"What is the demand for cloud architecture and security professionals?",
"What is the duration of Cloud Architecture and Security program of RACE?",
"When do you start the new batch for M.Sc. in Cloud Architecture and Security program?",
"Is industry experience mandatory for joining M. Sc. in Cloud Architecture and Security of RACE?",
"Is M. Sc. in Cloud Architecture and Security program of RACE accredited?",
"How do you promote experiential learning in M.Sc. in Cloud Architecture and Security of RACE?",
"Which are the short-term programs available at RACE?",
"When do short-term programs of RACE commence?",
"What are the criteria for certification programs of RACE?",
"How can a certification program of RACE beneficial for me?",
"Are there any program offered online by RACE?",
"Do I receive a recognized certificate for short-term programs of RACE? ",
"What is the duration of short-term programs of RACE?",
"How do I apply for the short-term programs of RACE?",
"Do you have specific trainers for certification programs of RACE?",
"Will I be considered an alumnus of RACE after completing a short-term program?"]

print(li[56-1])